### ISSUE TITLE
Init failure: TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by wraithrmm** [project-alice-assistant/project-alice-docker#10]
**Describe the bug**
Does anyone know what might cause this error during init?

**To Reproduce**
Just build the image and then run Alice to have her initialise.

**Screenshots/Error Codes**

#74 0.252 [Initializer]      Starting Project Alice initialization
#74 0.283 Traceback (most recent call last):
#74 0.283   File "main.py", line 68, in <module>
#74 0.283     Initializer().initProjectAlice()
#74 0.283   File "/root/ProjectAlice/core/Initializer.py", line 343, in initProjectAlice
#74 0.283     if not self._preInit.start():
#74 0.283   File "/root/ProjectAlice/core/Initializer.py", line 100, in start
#74 0.283     self.initConfs = self.loadConfig()
#74 0.283   File "/root/ProjectAlice/core/Initializer.py", line 148, in loadConfig
#74 0.283     if float(initConfs['version']) < VERSION:
#74 0.283 TypeError: float() argument must be a string or a number, not 'NoneType'
#74 ERROR: executor failed running [/bin/sh -c set -x &&         cd ~/ProjectAlice/ &&         . ~/.bashrc &&         python3.7 main.py]: exit code: 1

**Platform:**
AMD64

**Additional context**
I have checked the /root/ProjectAlice.yaml file and it's there and looks OK to me on face value. If it makes a difference, this is with the b4 codebase.

**Comment by wraithrmm** [comment]
This has ben mitigated for now by running initiation on Master before THEN switching over to the Beta branch.

Ideally, initialisation should work on all branches also, so I'm keeping this issue open to allow us to re-visit it at some point.
