### ISSUE TITLE
Build failing due to snips-nlu not installing sue to setuptools_rust being missing

### ISSUE THREAD

**Issue by wraithrmm** [project-alice-assistant/project-alice-docker#3]
```
#18 [linux/arm/v6 12/18] RUN set -x &&         cd ~/ProjectAlice/ &&        ...
#18 261.4 Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
#18 261.6 Processing ./snips_nlu-0.20.2-py3-none-any.whl
#18 262.0 Collecting snips-nlu-parsers<0.5,>=0.3.1 (from snips-nlu==0.20.2)
#18 263.8   Downloading https://files.pythonhosted.org/packages/cf/55/0c6e184e997c160c424e8da2f232673da2551fcb09628eb0f94e4f2d150c/snips_nlu_parsers-0.4.3.tar.gz
#18 265.5     Complete output from command python setup.py egg_info:
#18 265.5     Traceback (most recent call last):
#18 265.5       File "<string>", line 1, in <module>
#18 265.5       File "/tmp/pip-install-yfm0sy17/snips-nlu-parsers/setup.py", line 8, in <module>
#18 265.5         from setuptools_rust import Binding, RustExtension
#18 265.5     ModuleNotFoundError: No module named 'setuptools_rust'
#18 265.5     
#18 265.5     ----------------------------------------
#18 265.5 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yfm0sy17/snips-nlu-parsers/
#18 265.7 You are using pip version 10.0.1, however version 20.2.4 is available.
#18 265.7 You should consider upgrading via the 'pip install --upgrade pip' command.
#18 267.2 Missing key **stayCompletlyOffline** in provided yaml file.
#18 267.2 Missing key **ttsType** in provided yaml file.
#18 267.2 Traceback (most recent call last):
#18 267.2   File "/root/ProjectAlice/core/Initializer.py", line 495, in initProjectAlice
#18 267.2     pkg_resources.require('snips-nlu')
#18 267.2   File "/root/ProjectAlice/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
#18 267.2     needed = self.resolve(parse_requirements(requirements))
#18 267.2   File "/root/ProjectAlice/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
#18 267.2     raise DistributionNotFound(req, requirers)
#18 267.2 pkg_resources.DistributionNotFound: The 'snips-nlu' distribution was not found and is required by the application
#18 267.2 
#18 267.2 During handling of the above exception, another exception occurred:
#18 267.2 
#18 267.2 Traceback (most recent call last):
#18 267.2   File "initializer.py", line 68, in <module>
#18 267.2   File "/root/ProjectAlice/core/Initializer.py", line 517, in initProjectAlice
#18 267.2     subprocess.run(['./venv/bin/snips-nlu', 'download', confs['activeLanguage']])
#18 267.2   File "/usr/local/lib/python3.7/subprocess.py", line 453, in run
#18 267.2     with Popen(*popenargs, **kwargs) as process:
#18 267.2   File "/usr/local/lib/python3.7/subprocess.py", line 756, in __init__
#18 267.2     restore_signals, start_new_session)
#18 267.2   File "/usr/local/lib/python3.7/subprocess.py", line 1499, in _execute_child
#18 267.2     raise child_exception_type(errno_num, err_msg, err_filename)
#18 267.2 FileNotFoundError: [Errno 2] No such file or directory: './venv/bin/snips-nlu': './venv/bin/snips-nlu'
#18 ERROR: executor failed running [/bin/sh -c set -x &&         cd ~/ProjectAlice/ &&         cp /initializer.py ~/ProjectAlice/ &&         ./venv/bin/python initializer.py &&         cat /services-to-start.config]: buildkit-runc did not terminate successfully

```

**Comment by wraithrmm** [comment]
This is now only affecting intel and arm64 atm. I changed the base image being used with came with a more stable python 3.7, but this has not fixed it for all platforms.

I'm gonna try adding in some extra code to sort this out for these other platforms.

**Comment by wraithrmm** [comment]
We don't care about these platform for now, so this has been parked.

**Comment by wraithrmm** [comment]
Maniac has made the following suggestion which would get this working:

> #To install Snips on a x64 platform we need the following cahnges to ProjectAlice/core/Initializer.py:
> 
> Replace lines 380 - 394:
> 
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-platform-common_0.64.0_armhf.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-nlu_0.64.0_armhf.deb'])
> 	subprocess.run(['sudo', 'systemctl', 'stop', 'snips-nlu'])
> 	subprocess.run(['sudo', 'systemctl', 'disable', 'snips-nlu'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-hotword_0.64.0_armhf.deb'])
> 	subprocess.run(['sudo', 'systemctl', 'stop', 'snips-hotword'])
> 	subprocess.run(['sudo', 'systemctl', 'disable', 'snips-hotword'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-hotword-model-heysnipsv4_0.64.0_armhf.deb'])
> 
> 	subprocess.run(['wget', 'http://ftp.us.debian.org/debian/pool/non-free/s/svox/libttspico0_1.0+git20130326-9_armhf.deb'])
> 	subprocess.run(['wget', 'http://ftp.us.debian.org/debian/pool/non-free/s/svox/libttspico-utils_1.0+git20130326-9_armhf.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', './libttspico0_1.0+git20130326-9_armhf.deb', './libttspico-utils_1.0+git20130326-9_armhf.deb'])
> 
> 	subprocess.run(['rm', 'libttspico0_1.0+git20130326-9_armhf.deb'])
> 	subprocess.run(['rm', 'libttspico-utils_1.0+git20130326-9_armhf.deb'])
> 
> With something like this:
> 
> if Do_Platform_Check = ARM
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-platform-common_0.64.0_armhf.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-nlu_0.64.0_armhf.deb'])
> 	subprocess.run(['sudo', 'systemctl', 'stop', 'snips-nlu'])
> 	subprocess.run(['sudo', 'systemctl', 'disable', 'snips-nlu'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-hotword_0.64.0_armhf.deb'])
> 	subprocess.run(['sudo', 'systemctl', 'stop', 'snips-hotword'])
> 	subprocess.run(['sudo', 'systemctl', 'disable', 'snips-hotword'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', f'./system/snips/snips-hotword-model-heysnipsv4_0.64.0_armhf.deb'])
> 
> 	subprocess.run(['wget', 'http://ftp.us.debian.org/debian/pool/non-free/s/svox/libttspico0_1.0+git20130326-9_armhf.deb'])
> 	subprocess.run(['wget', 'http://ftp.us.debian.org/debian/pool/non-free/s/svox/libttspico-utils_1.0+git20130326-9_armhf.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', './libttspico0_1.0+git20130326-9_armhf.deb', './libttspico-utils_1.0+git20130326-9_armhf.deb'])
> 
> 	subprocess.run(['rm', 'libttspico0_1.0+git20130326-9_armhf.deb'])
> 	subprocess.run(['rm', 'libttspico-utils_1.0+git20130326-9_armhf.deb'])
> else:
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-platform-common_0.64.0_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-nlu_0.64.0_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-hotword_0.64.0_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-hotword-model-heysnipsv4_0.64.0_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-kaldi-atlas_0.26.1_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-asr_0.64.0_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-platform-voice_0.64.0_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/stretch/pool/s/sn/snips-watch_0.64.0_amd64.deb'])
> 	subprocess.run(['wget', '--content-disposition', 'https://debian.snips.ai/jessie/pool/s/sn/snips-asr-model-en-500MB_0.6.0-alpha.4_amd64.deb'])
> 
> 	subprocess.run(['sudo', 'apt', 'install', '-y', '--allow-unauthenticated', f'./system/snips/snips-platform-common_0.64.0_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y', '--allow-unauthenticated', f'./system/snips/snips-nlu_0.64.0_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y, '--allow-unauthenticated'', f'./system/snips/snips-hotword_0.64.0_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y, '--allow-unauthenticated'', f'./system/snips/snips-hotword-model-heysnipsv4_0.64.0_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y, '--allow-unauthenticated'', f'./system/snips/snips-kaldi-atlas_0.26.1_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y, '--allow-unauthenticated'', f'./system/snips/snips-asr_0.64.0_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y, '--allow-unauthenticated'', f'./system/snips/snips-asr-model-en-500MB_0.6.0-alpha.4_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y, '--allow-unauthenticated'', f'./system/snips/snips-platform-voice_0.64.0_amd64.deb'])
> 	subprocess.run(['sudo', 'apt', 'install', '-y, '--allow-unauthenticated'', f'./system/snips/snips-watch_0.64.0_amd64.deb'])
> 
> 	subprocess.run(['rm', 'snips-platform-common_0.64.0_amd64.deb'])
> 	subprocess.run(['rm', 'snips-nlu_0.64.0_amd64.deb'])
> 	subprocess.run(['rm', 'snips-hotword_0.64.0_amd64.deb'])
> 	subprocess.run(['rm', 'snips-hotword-model-heysnipsv4_0.64.0_amd64.deb'])
> 	subprocess.run(['rm', 'snips-kaldi-atlas_0.26.1_amd64.deb'])
> 	subprocess.run(['rm', 'snips-asr_0.64.0_amd64.deb'])
> 	subprocess.run(['rm', 'snips-asr-model-en-500MB_0.6.0-alpha.4_amd64.deb'])
> 	subprocess.run(['rm', 'snips-platform-voice_0.64.0_amd64.deb'])
> 	subprocess.run(['rm', 'snips-watch_0.64.0_amd64.deb'])
> 	
> Note:
> Apologies - Python is not my thing, so the above might have errors!
